name: pyjanitor-dev
channels:
- defaults
- rdkit
- conda-forge
- ericmjl
dependencies:
- python >= 3.6
- pandas >= 0.24.0
- pytest
- ipython
- ipykernel
- sphinx
- recommonmark
- pipreqs
- flake8
- xlrd
- missingno
- scikit-learn
- twine
- bumpversion
- pytest-cov
- pandas-flavor
- conda
- pylint
- biopython
- doc8
- nox
- cairo
- rdkit
- pandas-flavor
- mypy
- pyflakes
- black
- hypothesis>=4.4.0
- jupyterlab
- xorg-libxrender
- nbsphinx
- pip
- pytest-azurepipelines
- python-language-server
- sphinxcontrib-fulltoc
