[tool.black]
line-length = 79
target-version = ['py36', 'py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | venv
)/
'''

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-semiprivate = false
ignore-private = false
ignore-module = false
fail-under = 100
exclude = ["setup.py", "docs", "build"]
verbose = 2
quiet = false
