steps:
  - script: |
      $(activate.command) pyjanitor-dev
      make lint
    displayName: 'Code style check: pycodestyle'
  - script: |
      $(activate.command) pyjanitor-dev
      black --check -l 79 .
    displayName: 'Code style check: black'
  - script: |
      $(activate.command) pyjanitor-dev
      make test
      bash <(curl -s https://codecov.io/bash)
    displayName: 'Run all pyjanitor tests.'
  - script: |
      $(activate.command) pyjanitor-dev
      make notebooks
    displayName: 'Test that all notebooks execute correctly.'
  - script: |
      $(activate.command) pyjanitor-dev
      make docs
    displayName: 'Test that HTML docs all build correctly.'
