steps:
  - script: |
      $(activate.command) pyjanitor-dev
      make lint
    displayName: 'Code style check: flake8'
  - script: |
      $(activate.command) pyjanitor-dev
      make blackecheck
    displayName: 'Code style check: black'
  - script: |
      $(activate.command) pyjanitor-dev
      make test
    displayName: 'Run all pyjanitor tests.'
  - script: |
      $(activate.command) pyjanitor-dev
      checkautodoc
    displayName: 'Check that all general functions have been added to docs.'
  - script: |
      $(activate.command) pyjanitor-dev
      python -m ipykernel install --user --name pyjanitor-dev
      jupyter nbconvert --to notebook --config nbconvert_config.py --execute --template full
    displayName: 'Test that all notebooks execute correctly.'
  - script: |
      $(activate.command) pyjanitor-dev
      make docs
    displayName: 'Test that HTML docs all build correctly.'
  - script: |
      $(activate.command) pyjanitor-dev
      bash <(curl -s https://codecov.io/bash) -t c4aaeb6c-be8f-44b2-a529-6871f3537261
    displayName: 'Upload code coverage.'
